[package]
name = "tolower_uopt"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
rand = "*"

[[bench]]
name = "my_benchmark"
harness = false